import { Question, Subject } from './types';

// ─── Все предметы ЕНТ ────────────────────────────────────────────────────────
export const ALL_SUBJECTS: Subject[] = [
  { id: 'math_lit',     label: 'Мат. грамотность',    color: 'indigo',  required: true },
  { id: 'reading',      label: 'Грамотность чтения',  color: 'violet',  required: true },
  { id: 'history_kz',   label: 'История Казахстана',  color: 'amber',   required: true },
  { id: 'math',         label: 'Математика',           color: 'blue',    required: false },
  { id: 'physics',      label: 'Физика',               color: 'yellow',  required: false },
  { id: 'chemistry',    label: 'Химия',                color: 'green',   required: false },
  { id: 'biology',      label: 'Биология',             color: 'emerald', required: false },
  { id: 'geography',    label: 'География',            color: 'teal',    required: false },
  { id: 'informatics',  label: 'Информатика',          color: 'cyan',    required: false },
  { id: 'english',      label: 'Английский язык',      color: 'rose',    required: false },
  { id: 'russian',      label: 'Русский язык',         color: 'pink',    required: false },
  { id: 'world_history',label: 'Всемирная история',   color: 'orange',  required: false },
];

// ─── Банк вопросов ────────────────────────────────────────────────────────────
export const QUESTIONS_BANK: Record<string, Question[]> = {

  // ══════════════════════════════════════════════════════════
  //  МАТЕМАТИКА
  // ══════════════════════════════════════════════════════════
  math: [
    // Логарифмы
    { id: 'm1', subject: 'math', topic: 'Логарифмы',
      text: 'Вычислите: log₂ 16 + log₃ 27',
      options: ['5', '7', '8', '12'], correctAnswer: '7', difficulty: 'easy',
      explanation: 'log₂ 16 = 4 (2⁴=16), log₃ 27 = 3 (3³=27). Итого: 4+3=7.' },
    { id: 'm2', subject: 'math', topic: 'Логарифмы',
      text: 'Найдите log₅ 125',
      options: ['2', '3', '4', '5'], correctAnswer: '3', difficulty: 'easy',
      explanation: '5³ = 125, значит log₅ 125 = 3.' },
    { id: 'm3', subject: 'math', topic: 'Логарифмы',
      text: 'Упростите: log₂ 8 − log₂ 2',
      options: ['1', '2', '3', '4'], correctAnswer: '2', difficulty: 'easy',
      explanation: 'log₂ 8 = 3, log₂ 2 = 1. Разность: 3−1=2.' },
    { id: 'm4', subject: 'math', topic: 'Логарифмы',
      text: 'Решите уравнение: log₃ x = 4',
      options: ['12', '64', '81', '27'], correctAnswer: '81', difficulty: 'medium',
      explanation: 'log₃ x = 4 ⟹ x = 3⁴ = 81.' },
    { id: 'm5', subject: 'math', topic: 'Логарифмы',
      text: 'Вычислите: log₁₀ 1000 + log₁₀ 0.001',
      options: ['0', '6', '−6', '3'], correctAnswer: '0', difficulty: 'medium',
      explanation: 'log₁₀ 1000 = 3, log₁₀ 0.001 = −3. Сумма: 3+(−3)=0.' },
    { id: 'm6', subject: 'math', topic: 'Логарифмы',
      text: 'Найдите x: log₂(x+1) = 3',
      options: ['5', '6', '7', '8'], correctAnswer: '7', difficulty: 'medium',
      explanation: 'x+1 = 2³ = 8, значит x = 7.' },

    // Тригонометрия
    { id: 'm7', subject: 'math', topic: 'Тригонометрия',
      text: 'Чему равно sin(π/6)?',
      options: ['0', '1/2', '√2/2', '√3/2'], correctAnswer: '1/2', difficulty: 'easy',
      explanation: 'sin(30°) = 1/2 — стандартное табличное значение.' },
    { id: 'm8', subject: 'math', topic: 'Тригонометрия',
      text: 'Чему равно cos(60°)?',
      options: ['√3/2', '1/2', '0', '1'], correctAnswer: '1/2', difficulty: 'easy',
      explanation: 'cos(60°) = 1/2 — табличное значение.' },
    { id: 'm9', subject: 'math', topic: 'Тригонометрия',
      text: 'Упростите: sin²x + cos²x',
      options: ['0', '2', '1', '−1'], correctAnswer: '1', difficulty: 'easy',
      explanation: 'Основное тригонометрическое тождество: sin²x + cos²x = 1.' },
    { id: 'm10', subject: 'math', topic: 'Тригонометрия',
      text: 'Чему равно tg(45°)?',
      options: ['0', '1', '√3', 'Не существует'], correctAnswer: '1', difficulty: 'easy',
      explanation: 'tg(45°) = sin45°/cos45° = (√2/2)/(√2/2) = 1.' },
    { id: 'm11', subject: 'math', topic: 'Тригонометрия',
      text: 'Решите уравнение: 2sin x = √2. Наименьшее положительное x?',
      options: ['π/6', 'π/4', 'π/3', 'π/2'], correctAnswer: 'π/4', difficulty: 'medium',
      explanation: 'sin x = √2/2, значит x = π/4 = 45°.' },

    // Производная
    { id: 'm12', subject: 'math', topic: 'Производная',
      text: 'Найдите f\'(x), если f(x) = x³ − 3x² + 5',
      options: ['3x² − 6x', 'x² − 3x', '3x² − 6', '3x³ − 6x'], correctAnswer: '3x² − 6x', difficulty: 'medium',
      explanation: '(x³)\'=3x², (3x²)\'=6x, (5)\'=0. Итого: 3x²−6x.' },
    { id: 'm13', subject: 'math', topic: 'Производная',
      text: 'Производная функции f(x) = 5x⁴ − 2x + 7',
      options: ['20x³ − 2', '20x³ + 2', '5x³ − 2', '4x³ − 2'], correctAnswer: '20x³ − 2', difficulty: 'medium',
      explanation: '(5x⁴)\'=20x³, (2x)\'=2, (7)\'=0. Ответ: 20x³−2.' },
    { id: 'm14', subject: 'math', topic: 'Производная',
      text: 'При каком x функция f(x) = x² − 4x + 3 имеет минимум?',
      options: ['x=1', 'x=2', 'x=3', 'x=4'], correctAnswer: 'x=2', difficulty: 'medium',
      explanation: 'f\'(x) = 2x−4 = 0 ⟹ x = 2. f\'\'(2) = 2 > 0 — минимум.' },

    // Уравнения
    { id: 'm15', subject: 'math', topic: 'Уравнения',
      text: 'Решите: x² − 5x + 6 = 0',
      options: ['x=1, x=6', 'x=2, x=3', 'x=−2, x=3', 'x=−3, x=−2'], correctAnswer: 'x=2, x=3', difficulty: 'easy',
      explanation: 'По теореме Виета: сумма=5, произведение=6 → x=2, x=3.' },
    { id: 'm16', subject: 'math', topic: 'Уравнения',
      text: 'Решите уравнение: 2x + 3 = 11',
      options: ['x=3', 'x=4', 'x=5', 'x=7'], correctAnswer: 'x=4', difficulty: 'easy',
      explanation: '2x = 11−3 = 8, x = 4.' },
    { id: 'm17', subject: 'math', topic: 'Уравнения',
      text: 'Решите: 3ˣ = 81',
      options: ['x=3', 'x=4', 'x=5', 'x=27'], correctAnswer: 'x=4', difficulty: 'medium',
      explanation: '3⁴ = 81, значит x = 4.' },
    { id: 'm18', subject: 'math', topic: 'Уравнения',
      text: 'Дискриминант уравнения 2x²−3x+1=0:',
      options: ['1', '2', '7', '17'], correctAnswer: '1', difficulty: 'medium',
      explanation: 'D = b²−4ac = 9−8 = 1.' },

    // Геометрия
    { id: 'm19', subject: 'math', topic: 'Планиметрия',
      text: 'Площадь круга с радиусом 5 см (π≈3.14)?',
      options: ['31.4 см²', '78.5 см²', '15.7 см²', '25 см²'], correctAnswer: '78.5 см²', difficulty: 'easy',
      explanation: 'S = πr² = 3.14 × 25 = 78.5 см².' },
    { id: 'm20', subject: 'math', topic: 'Планиметрия',
      text: 'В прямоугольном треугольнике катеты 3 и 4. Гипотенуза?',
      options: ['5', '6', '7', '√7'], correctAnswer: '5', difficulty: 'easy',
      explanation: 'По теореме Пифагора: √(9+16) = √25 = 5.' },
    { id: 'm21', subject: 'math', topic: 'Планиметрия',
      text: 'Площадь параллелограмма, основание=8, высота=5',
      options: ['13', '26', '40', '20'], correctAnswer: '40', difficulty: 'easy',
      explanation: 'S = a·h = 8·5 = 40.' },
    { id: 'm22', subject: 'math', topic: 'Стереометрия',
      text: 'Объём куба со стороной 3 см?',
      options: ['9 см³', '18 см³', '27 см³', '36 см³'], correctAnswer: '27 см³', difficulty: 'easy',
      explanation: 'V = a³ = 3³ = 27 см³.' },
    { id: 'm23', subject: 'math', topic: 'Стереометрия',
      text: 'Площадь полной поверхности прямоугольного параллелепипеда 2×3×4?',
      options: ['24', '48', '52', '26'], correctAnswer: '52', difficulty: 'medium',
      explanation: 'S = 2(ab+bc+ac) = 2(6+12+8) = 2×26 = 52.' },

    // Прогрессии
    { id: 'm24', subject: 'math', topic: 'Прогрессии',
      text: 'Сумма 10 членов арифм. прогрессии, где a₁=2, d=3?',
      options: ['155', '120', '185', '140'], correctAnswer: '155', difficulty: 'medium',
      explanation: 'S₁₀ = 10/2 × (2×2 + 9×3) = 5 × 31 = 155.' },
    { id: 'm25', subject: 'math', topic: 'Прогрессии',
      text: '5-й член арифм. прогрессии a₁=3, d=4?',
      options: ['15', '17', '19', '23'], correctAnswer: '19', difficulty: 'easy',
      explanation: 'a₅ = a₁ + (5−1)d = 3+16 = 19.' },
    { id: 'm26', subject: 'math', topic: 'Прогрессии',
      text: '4-й член геометрической прогрессии b₁=2, q=3?',
      options: ['18', '27', '54', '16'], correctAnswer: '54', difficulty: 'medium',
      explanation: 'b₄ = b₁·q³ = 2·27 = 54.' },

    // Вероятность и векторы
    { id: 'm27', subject: 'math', topic: 'Вероятность',
      text: 'В урне 5 красных и 3 синих шара. Вероятность вытащить красный?',
      options: ['3/8', '5/8', '5/3', '1/2'], correctAnswer: '5/8', difficulty: 'easy',
      explanation: 'P = 5/(5+3) = 5/8.' },
    { id: 'm28', subject: 'math', topic: 'Вероятность',
      text: 'Монету бросают 2 раза. Вероятность двух орлов?',
      options: ['1/2', '1/3', '1/4', '1/6'], correctAnswer: '1/4', difficulty: 'easy',
      explanation: 'P = (1/2)×(1/2) = 1/4.' },
    { id: 'm29', subject: 'math', topic: 'Векторы',
      text: 'Длина вектора ā=(3; 4)?',
      options: ['7', '5', '12', '25'], correctAnswer: '5', difficulty: 'easy',
      explanation: '|ā| = √(9+16) = √25 = 5.' },
    { id: 'm30', subject: 'math', topic: 'Векторы',
      text: 'Скалярное произведение ā=(2;3) и b̄=(4;−1)?',
      options: ['5', '8', '11', '−5'], correctAnswer: '5', difficulty: 'medium',
      explanation: 'ā·b̄ = 2·4 + 3·(−1) = 8−3 = 5.' },

    // Неравенства
    { id: 'm31', subject: 'math', topic: 'Неравенства',
      text: 'Решите неравенство: 2x − 5 > 3',
      options: ['x > 4', 'x > 3', 'x < 4', 'x > −1'], correctAnswer: 'x > 4', difficulty: 'easy',
      explanation: '2x > 8 ⟹ x > 4.' },
    { id: 'm32', subject: 'math', topic: 'Неравенства',
      text: 'Решите: x² − 9 < 0',
      options: ['x < 3', 'x > −3', '−3 < x < 3', 'x < −3 или x > 3'], correctAnswer: '−3 < x < 3', difficulty: 'medium',
      explanation: 'x²<9 ⟹ |x|<3 ⟹ −3<x<3.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  МАТЕМАТИЧЕСКАЯ ГРАМОТНОСТЬ
  // ══════════════════════════════════════════════════════════
  math_lit: [
    { id: 'ml1', subject: 'math_lit', topic: 'Проценты',
      text: 'Товар стоит 12 000 тг. Скидка 25%. Итоговая цена?',
      options: ['9 000 тг', '10 000 тг', '8 500 тг', '3 000 тг'], correctAnswer: '9 000 тг', difficulty: 'easy',
      explanation: '12000 × 0.75 = 9000 тг.' },
    { id: 'ml2', subject: 'math_lit', topic: 'Проценты',
      text: 'Какой процент от числа 50 составляет число 10?',
      options: ['15%', '20%', '25%', '10%'], correctAnswer: '20%', difficulty: 'easy',
      explanation: '10/50 × 100% = 20%.' },
    { id: 'ml3', subject: 'math_lit', topic: 'Проценты',
      text: 'Зарплата 80 000 тг. Повысили на 15%. Новая зарплата?',
      options: ['88 000 тг', '90 000 тг', '92 000 тг', '95 000 тг'], correctAnswer: '92 000 тг', difficulty: 'easy',
      explanation: '80000 × 1.15 = 92 000 тг.' },
    { id: 'ml4', subject: 'math_lit', topic: 'Статистика',
      text: 'Данные: 5, 7, 3, 9, 1. Среднее арифметическое?',
      options: ['4', '5', '6', '7'], correctAnswer: '5', difficulty: 'easy',
      explanation: '(5+7+3+9+1)/5 = 25/5 = 5.' },
    { id: 'ml5', subject: 'math_lit', topic: 'Статистика',
      text: 'Медиана набора: 2, 4, 6, 8, 10?',
      options: ['4', '5', '6', '8'], correctAnswer: '6', difficulty: 'easy',
      explanation: 'Медиана — средний элемент (3-й из 5): 6.' },
    { id: 'ml6', subject: 'math_lit', topic: 'Статистика',
      text: 'Мода набора: 3, 5, 5, 7, 9, 5, 2?',
      options: ['3', '5', '7', '9'], correctAnswer: '5', difficulty: 'easy',
      explanation: 'Мода — наиболее часто встречающееся значение: 5 (три раза).' },
    { id: 'ml7', subject: 'math_lit', topic: 'Диаграммы',
      text: 'Из 200 учеников 40% выбрали физику. Сколько?',
      options: ['40', '60', '80', '100'], correctAnswer: '80', difficulty: 'easy',
      explanation: '200 × 0.40 = 80.' },
    { id: 'ml8', subject: 'math_lit', topic: 'Диаграммы',
      text: 'На диаграмме расходы: еда 30%, одежда 20%, транспорт 15%, остальное 35%. Если бюджет 60 000 тг, сколько на одежду?',
      options: ['9 000 тг', '12 000 тг', '15 000 тг', '18 000 тг'], correctAnswer: '12 000 тг', difficulty: 'easy',
      explanation: '60000 × 0.20 = 12 000 тг.' },
    { id: 'ml9', subject: 'math_lit', topic: 'Задачи',
      text: 'Поезд прошёл 360 км за 4 часа. Средняя скорость?',
      options: ['80 км/ч', '90 км/ч', '100 км/ч', '120 км/ч'], correctAnswer: '90 км/ч', difficulty: 'easy',
      explanation: 'v = 360/4 = 90 км/ч.' },
    { id: 'ml10', subject: 'math_lit', topic: 'Задачи',
      text: 'Велосипедист едет 15 км/ч 2 ч, затем 20 км/ч ещё 1 ч. Общий путь?',
      options: ['50 км', '55 км', '60 км', '65 км'], correctAnswer: '50 км', difficulty: 'medium',
      explanation: '15×2 + 20×1 = 30+20 = 50 км.' },
    { id: 'ml11', subject: 'math_lit', topic: 'Множества',
      text: 'A={1,2,3,4}, B={3,4,5,6}. Мощность A∩B?',
      options: ['2', '4', '6', '8'], correctAnswer: '2', difficulty: 'medium',
      explanation: 'A∩B = {3,4}. Мощность = 2.' },
    { id: 'ml12', subject: 'math_lit', topic: 'Множества',
      text: 'A={2,4,6}, B={4,6,8}. Найдите A∪B.',
      options: ['{4,6}', '{2,4,6,8}', '{2,8}', '{2,4,6,8,10}'], correctAnswer: '{2,4,6,8}', difficulty: 'medium',
      explanation: 'A∪B объединяет все элементы: {2,4,6,8}.' },
    { id: 'ml13', subject: 'math_lit', topic: 'Вероятность',
      text: 'Из 10 карточек с числами 1–10 вытащили одну. Вероятность чётного числа?',
      options: ['1/5', '2/5', '1/2', '3/5'], correctAnswer: '1/2', difficulty: 'easy',
      explanation: 'Чётных: 2,4,6,8,10 — пять штук. P = 5/10 = 1/2.' },
    { id: 'ml14', subject: 'math_lit', topic: 'Пространство и форма',
      text: 'Периметр прямоугольника 6×4?',
      options: ['10', '20', '24', '48'], correctAnswer: '20', difficulty: 'easy',
      explanation: 'P = 2(a+b) = 2(6+4) = 20.' },
    { id: 'ml15', subject: 'math_lit', topic: 'Пространство и форма',
      text: 'Площадь трапеции, основания 5 и 9, высота 4?',
      options: ['14', '20', '28', '36'], correctAnswer: '28', difficulty: 'medium',
      explanation: 'S = (a+b)/2 × h = (5+9)/2 × 4 = 7×4 = 28.' },

    // Изменение и зависимости
    { id: 'ml16', subject: 'math_lit', topic: 'Изменение и зависимости',
      text: 'Последовательность: 2, 5, 8, 11, … Следующий элемент?',
      options: ['12', '13', '14', '15'], correctAnswer: '14', difficulty: 'easy',
      explanation: 'Разность d=3. Следующий: 11+3=14.' },
    { id: 'ml17', subject: 'math_lit', topic: 'Изменение и зависимости',
      text: 'Если x=3, то 4x² − 2x + 1 = ?',
      options: ['25', '31', '37', '43'], correctAnswer: '31', difficulty: 'medium',
      explanation: '4·9 − 2·3 + 1 = 36−6+1 = 31.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ФИЗИКА
  // ══════════════════════════════════════════════════════════
  physics: [
    // Кинематика
    { id: 'ph1', subject: 'physics', topic: 'Кинематика',
      text: 'Тело: v₀=10 м/с, a=2 м/с². Скорость через 5 с?',
      options: ['15 м/с', '20 м/с', '25 м/с', '30 м/с'], correctAnswer: '20 м/с', difficulty: 'easy',
      explanation: 'v = v₀ + at = 10 + 2×5 = 20 м/с.' },
    { id: 'ph2', subject: 'physics', topic: 'Кинематика',
      text: 'Тело движется с ускорением 3 м/с² с покоя. Путь за 4 с?',
      options: ['12 м', '24 м', '48 м', '6 м'], correctAnswer: '24 м', difficulty: 'easy',
      explanation: 'S = v₀t + at²/2 = 0 + 3×16/2 = 24 м.' },
    { id: 'ph3', subject: 'physics', topic: 'Кинематика',
      text: 'Автомобиль проехал 120 км за 1.5 ч. Средняя скорость в м/с?',
      options: ['20 м/с', '22 м/с', '80 м/с', '133 м/с'], correctAnswer: '22 м/с', difficulty: 'medium',
      explanation: 'v = 120000/5400 ≈ 22.2 м/с.' },
    // Динамика
    { id: 'ph4', subject: 'physics', topic: 'Динамика',
      text: 'Сила 20 Н, масса 4 кг. Ускорение?',
      options: ['2 м/с²', '4 м/с²', '5 м/с²', '80 м/с²'], correctAnswer: '5 м/с²', difficulty: 'easy',
      explanation: 'a = F/m = 20/4 = 5 м/с².' },
    { id: 'ph5', subject: 'physics', topic: 'Динамика',
      text: 'Тело массой 10 кг движется с ускорением 4 м/с². Сила?',
      options: ['2.5 Н', '14 Н', '40 Н', '100 Н'], correctAnswer: '40 Н', difficulty: 'easy',
      explanation: 'F = ma = 10×4 = 40 Н.' },
    { id: 'ph6', subject: 'physics', topic: 'Динамика',
      text: 'Что утверждает 3-й закон Ньютона?',
      options: [
        'F=ma',
        'Тело в покое остаётся в покое',
        'Действие равно противодействию',
        'Скорость постоянна без сил'
      ], correctAnswer: 'Действие равно противодействию', difficulty: 'easy',
      explanation: '3-й закон Ньютона: силы действия и противодействия равны по модулю.' },
    // Законы сохранения
    { id: 'ph7', subject: 'physics', topic: 'Законы сохранения',
      text: 'Кинетическая энергия тела m=2 кг, v=10 м/с?',
      options: ['20 Дж', '100 Дж', '200 Дж', '400 Дж'], correctAnswer: '100 Дж', difficulty: 'easy',
      explanation: 'Eₖ = mv²/2 = 2×100/2 = 100 Дж.' },
    { id: 'ph8', subject: 'physics', topic: 'Законы сохранения',
      text: 'Потенциальная энергия тела m=3 кг, h=5 м (g=10 м/с²)?',
      options: ['15 Дж', '50 Дж', '150 Дж', '300 Дж'], correctAnswer: '150 Дж', difficulty: 'easy',
      explanation: 'Eₚ = mgh = 3×10×5 = 150 Дж.' },
    // Электричество
    { id: 'ph9', subject: 'physics', topic: 'Электричество',
      text: 'R=10 Ом, I=2 А. Напряжение?',
      options: ['5 В', '8 В', '12 В', '20 В'], correctAnswer: '20 В', difficulty: 'easy',
      explanation: 'U = IR = 2×10 = 20 В.' },
    { id: 'ph10', subject: 'physics', topic: 'Электричество',
      text: 'Мощность тока: U=220 В, I=5 А?',
      options: ['44 Вт', '215 Вт', '1100 Вт', '225 Вт'], correctAnswer: '1100 Вт', difficulty: 'easy',
      explanation: 'P = UI = 220×5 = 1100 Вт.' },
    { id: 'ph11', subject: 'physics', topic: 'Электричество',
      text: 'Два резистора 6 Ом и 3 Ом параллельно. Общее сопротивление?',
      options: ['9 Ом', '4.5 Ом', '3 Ом', '2 Ом'], correctAnswer: '2 Ом', difficulty: 'medium',
      explanation: '1/R = 1/6+1/3 = 1/6+2/6 = 3/6 = 1/2. R=2 Ом.' },
    // Термодинамика
    { id: 'ph12', subject: 'physics', topic: 'Термодинамика',
      text: 'При изотермическом процессе V увеличился в 2 раза. Что с давлением?',
      options: ['Увеличилось в 2 раза', 'Уменьшилось в 2 раза', 'Не изменилось', 'Уменьшилось в 4 раза'],
      correctAnswer: 'Уменьшилось в 2 раза', difficulty: 'medium',
      explanation: 'Закон Бойля-Мариотта: pV=const. V×2 → p/2.' },
    { id: 'ph13', subject: 'physics', topic: 'Термодинамика',
      text: 'Изохорный процесс — это процесс при постоянном:',
      options: ['Давлении', 'Объёме', 'Температуре', 'Количестве вещества'],
      correctAnswer: 'Объёме', difficulty: 'easy',
      explanation: 'Изохорный — от «хора» (объём). V=const.' },
    // Оптика
    { id: 'ph14', subject: 'physics', topic: 'Оптика',
      text: 'Скорость света в вакууме:',
      options: ['3×10⁶ м/с', '3×10⁸ м/с', '3×10¹⁰ м/с', '3×10⁵ км/с'], correctAnswer: '3×10⁸ м/с', difficulty: 'easy',
      explanation: 'c ≈ 3×10⁸ м/с — фундаментальная константа.' },
    { id: 'ph15', subject: 'physics', topic: 'Оптика',
      text: 'Какой закон описывает отражение света от зеркала?',
      options: ['Закон Фарадея', 'Закон Ома', 'Закон отражения', 'Закон Архимеда'],
      correctAnswer: 'Закон отражения', difficulty: 'easy',
      explanation: 'Угол падения = углу отражения — закон отражения.' },
    // Квантовая физика
    { id: 'ph16', subject: 'physics', topic: 'Квантовая физика',
      text: 'Фотоэффект открыл:',
      options: ['Ньютон', 'Эйнштейн', 'Герц', 'Планк'], correctAnswer: 'Герц', difficulty: 'medium',
      explanation: 'Генрих Герц обнаружил фотоэффект в 1887 г., объяснил Эйнштейн.' },
    { id: 'ph17', subject: 'physics', topic: 'Квантовая физика',
      text: 'Протон состоит из:',
      options: ['1 кварка', '2 кварков', '3 кварков', '4 кварков'],
      correctAnswer: '3 кварков', difficulty: 'hard',
      explanation: 'Протон: 2 up-кварка + 1 down-кварк = 3 кварка.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ХИМИЯ
  // ══════════════════════════════════════════════════════════
  chemistry: [
    { id: 'ch1', subject: 'chemistry', topic: 'Строение атома',
      text: 'Сколько протонов у кислорода (O, №8)?',
      options: ['6', '7', '8', '16'], correctAnswer: '8', difficulty: 'easy',
      explanation: 'Порядковый номер = число протонов = 8.' },
    { id: 'ch2', subject: 'chemistry', topic: 'Строение атома',
      text: 'Период и группа хлора (Cl, №17) в ПСХЭ?',
      options: ['2 период, VI группа', '3 период, VII группа', '3 период, VI группа', '2 период, VII группа'],
      correctAnswer: '3 период, VII группа', difficulty: 'medium',
      explanation: 'Cl — 3-й период (3 электронных слоя), VII группа (7 валентных e⁻).' },
    { id: 'ch3', subject: 'chemistry', topic: 'Строение атома',
      text: 'Сколько нейтронов у ²⁷Al (атомный номер 13)?',
      options: ['13', '14', '27', '40'], correctAnswer: '14', difficulty: 'medium',
      explanation: 'N = A − Z = 27 − 13 = 14.' },
    { id: 'ch4', subject: 'chemistry', topic: 'Реакции',
      text: 'При горении CH₄ образуется:',
      options: ['CO + H₂O', 'CO₂ + H₂O', 'C + H₂', 'CH₃OH'], correctAnswer: 'CO₂ + H₂O', difficulty: 'easy',
      explanation: 'CH₄ + 2O₂ → CO₂ + 2H₂O.' },
    { id: 'ch5', subject: 'chemistry', topic: 'Реакции',
      text: 'Тип реакции: A + B → AB',
      options: ['Разложение', 'Соединение', 'Замещение', 'Обмен'],
      correctAnswer: 'Соединение', difficulty: 'easy',
      explanation: 'Два вещества образуют одно — реакция соединения.' },
    { id: 'ch6', subject: 'chemistry', topic: 'Органика',
      text: 'Какой класс веществ имеет формулу CₙH₂ₙ?',
      options: ['Алканы', 'Алкены', 'Алкины', 'Арены'], correctAnswer: 'Алкены', difficulty: 'medium',
      explanation: 'CₙH₂ₙ — общая формула алкенов (одна двойная связь C=C).' },
    { id: 'ch7', subject: 'chemistry', topic: 'Органика',
      text: 'CH₃COOH — это:',
      options: ['Уксусная кислота', 'Молочная кислота', 'Этанол', 'Уксусный альдегид'],
      correctAnswer: 'Уксусная кислота', difficulty: 'easy',
      explanation: 'CH₃COOH — формула уксусной (этановой) кислоты.' },
    { id: 'ch8', subject: 'chemistry', topic: 'Органика',
      text: 'Формула этана?',
      options: ['CH₄', 'C₂H₄', 'C₂H₆', 'C₃H₈'], correctAnswer: 'C₂H₆', difficulty: 'easy',
      explanation: 'Этан — 2 атома C, 6 атомов H: C₂H₆.' },
    { id: 'ch9', subject: 'chemistry', topic: 'Электролиз',
      text: 'Что происходит на катоде при электролизе?',
      options: ['Окисление', 'Восстановление', 'Нейтрализация', 'Гидролиз'],
      correctAnswer: 'Восстановление', difficulty: 'medium',
      explanation: 'Катод (−) — восстановление (приём электронов).' },
    { id: 'ch10', subject: 'chemistry', topic: 'Электролиз',
      text: 'На аноде при электролизе происходит:',
      options: ['Восстановление', 'Окисление', 'Нейтрализация', 'Диссоциация'],
      correctAnswer: 'Окисление', difficulty: 'medium',
      explanation: 'Анод (+) — окисление (отдача электронов).' },
    { id: 'ch11', subject: 'chemistry', topic: 'Молярная масса',
      text: 'Молярная масса H₂O?',
      options: ['8 г/моль', '17 г/моль', '18 г/моль', '20 г/моль'], correctAnswer: '18 г/моль', difficulty: 'easy',
      explanation: 'M(H₂O) = 2×1 + 16 = 18 г/моль.' },
    { id: 'ch12', subject: 'chemistry', topic: 'Молярная масса',
      text: 'Количество молей в 44 г CO₂ (M=44 г/моль)?',
      options: ['0.5 моль', '1 моль', '2 моль', '4 моль'], correctAnswer: '1 моль', difficulty: 'easy',
      explanation: 'n = m/M = 44/44 = 1 моль.' },
    { id: 'ch13', subject: 'chemistry', topic: 'Химическое равновесие',
      text: 'Катализатор влияет на:',
      options: ['Смещение равновесия', 'Скорость прямой и обратной реакций', 'Только прямую реакцию', 'Концентрацию продуктов'],
      correctAnswer: 'Скорость прямой и обратной реакций', difficulty: 'medium',
      explanation: 'Катализатор ускоряет обе реакции одинаково, не смещая равновесия.' },
    { id: 'ch14', subject: 'chemistry', topic: 'Периодический закон',
      text: 'Какое свойство атомов увеличивается слева направо в периоде ПСХЭ?',
      options: ['Атомный радиус', 'Металлические свойства', 'Электроотрицательность', 'Число электронных слоёв'],
      correctAnswer: 'Электроотрицательность', difficulty: 'medium',
      explanation: 'В периоде слева→вправо: заряд ядра растёт, радиус уменьшается, электроотрицательность растёт.' },
    { id: 'ch15', subject: 'chemistry', topic: 'Окислительно-восстановительные реакции',
      text: 'В реакции Zn + 2HCl → ZnCl₂ + H₂, цинк является:',
      options: ['Окислителем', 'Восстановителем', 'Катализатором', 'Средой'],
      correctAnswer: 'Восстановителем', difficulty: 'medium',
      explanation: 'Zn отдаёт электроны (Zn⁰→Zn²⁺) — восстановитель.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  БИОЛОГИЯ
  // ══════════════════════════════════════════════════════════
  biology: [
    { id: 'bi1', subject: 'biology', topic: 'Клетка',
      text: 'Где синтезируются белки в клетке?',
      options: ['Ядро', 'Митохондрия', 'Рибосома', 'Лизосома'], correctAnswer: 'Рибосома', difficulty: 'easy',
      explanation: 'Рибосомы — органоиды синтеза белка.' },
    { id: 'bi2', subject: 'biology', topic: 'Клетка',
      text: '"Энергетическая станция клетки" — это:',
      options: ['Рибосома', 'Митохондрия', 'Ядро', 'Вакуоль'],
      correctAnswer: 'Митохондрия', difficulty: 'easy',
      explanation: 'Митохондрии синтезируют АТФ — основной источник энергии клетки.' },
    { id: 'bi3', subject: 'biology', topic: 'Клетка',
      text: 'Чем растительная клетка отличается от животной?',
      options: [
        'Наличием ядра',
        'Наличием клеточной стенки и хлоропластов',
        'Наличием митохондрий',
        'Наличием рибосом'
      ], correctAnswer: 'Наличием клеточной стенки и хлоропластов', difficulty: 'easy',
      explanation: 'Растительная клетка имеет клеточную стенку из целлюлозы и хлоропласты.' },
    { id: 'bi4', subject: 'biology', topic: 'Генетика',
      text: 'Сколько хромосом в соматической клетке человека?',
      options: ['23', '46', '48', '92'], correctAnswer: '46', difficulty: 'easy',
      explanation: '46 хромосом (23 пары) в диплоидных клетках.' },
    { id: 'bi5', subject: 'biology', topic: 'Генетика',
      text: 'Нуклеотиды ДНК:',
      options: ['A, U, G, C', 'A, T, G, C', 'A, T, U, C', 'A, G, T, U'], correctAnswer: 'A, T, G, C', difficulty: 'medium',
      explanation: 'ДНК: Аденин, Тимин, Гуанин, Цитозин. В РНК — Урацил вместо Тимина.' },
    { id: 'bi6', subject: 'biology', topic: 'Генетика',
      text: 'По первому закону Менделя при скрещивании AA × aa гибриды F1:',
      options: ['Все аа', 'Все Aa', '50% AA, 50% aa', '25% AA, 50% Aa, 25% aa'],
      correctAnswer: 'Все Aa', difficulty: 'medium',
      explanation: '1-й закон Менделя: все гибриды F1 единообразны — Aa.' },
    { id: 'bi7', subject: 'biology', topic: 'Фотосинтез',
      text: 'В каком органоиде происходит фотосинтез?',
      options: ['Митохондрия', 'Хлоропласт', 'Вакуоль', 'Ядро'], correctAnswer: 'Хлоропласт', difficulty: 'easy',
      explanation: 'Хлоропласты содержат хлорофилл для фотосинтеза.' },
    { id: 'bi8', subject: 'biology', topic: 'Фотосинтез',
      text: 'Уравнение фотосинтеза: 6CO₂ + 6H₂O → ?',
      options: ['C₆H₁₂O₆ + 6O₂', '6CO₂ + 6O₂', 'C₆H₁₂O₆ + 6CO₂', '6H₂O + 6O₂'],
      correctAnswer: 'C₆H₁₂O₆ + 6O₂', difficulty: 'medium',
      explanation: 'Продукты фотосинтеза — глюкоза и кислород.' },
    { id: 'bi9', subject: 'biology', topic: 'Эволюция',
      text: 'Кто разработал теорию естественного отбора?',
      options: ['Ламарк', 'Мендель', 'Дарвин', 'Вавилов'], correctAnswer: 'Дарвин', difficulty: 'easy',
      explanation: 'Чарлз Дарвин — автор теории эволюции путём естественного отбора.' },
    { id: 'bi10', subject: 'biology', topic: 'Эволюция',
      text: 'Движущая сила эволюции по Дарвину:',
      options: ['Мутации', 'Упражнение органов', 'Естественный отбор', 'Изоляция'],
      correctAnswer: 'Естественный отбор', difficulty: 'easy',
      explanation: 'По Дарвину, главная движущая сила — естественный отбор.' },
    { id: 'bi11', subject: 'biology', topic: 'Пищеварение',
      text: 'Какой орган отвечает за переваривание с помощью кислоты и ферментов?',
      options: ['Печень', 'Желудок', 'Селезёнка', 'Тонкий кишечник'],
      correctAnswer: 'Желудок', difficulty: 'easy',
      explanation: 'Желудок содержит соляную кислоту и ферменты, расщепляющие белки.' },
    { id: 'bi12', subject: 'biology', topic: 'Пищеварение',
      text: 'Где происходит основное всасывание питательных веществ?',
      options: ['Желудок', 'Тонкий кишечник', 'Толстый кишечник', 'Пищевод'],
      correctAnswer: 'Тонкий кишечник', difficulty: 'easy',
      explanation: 'Тонкий кишечник — основное место всасывания питательных веществ.' },
    { id: 'bi13', subject: 'biology', topic: 'Размножение',
      text: 'Митоз — это деление клетки, в результате которого:',
      options: [
        'Образуются 4 гаплоидные клетки',
        'Образуются 2 диплоидные клетки',
        'Образуются 2 гаплоидные клетки',
        'Клетка погибает'
      ], correctAnswer: 'Образуются 2 диплоидные клетки', difficulty: 'medium',
      explanation: 'Митоз: 1 клетка → 2 дочерние с тем же набором хромосом (2n).' },
    { id: 'bi14', subject: 'biology', topic: 'Нервная система',
      text: 'Структурная единица нервной системы:',
      options: ['Миоцит', 'Нейрон', 'Нефрон', 'Аксон'],
      correctAnswer: 'Нейрон', difficulty: 'easy',
      explanation: 'Нейрон — основная структурная и функциональная единица нервной системы.' },
    { id: 'bi15', subject: 'biology', topic: 'Экология',
      text: 'Первичные продуценты в экосистеме — это:',
      options: ['Хищники', 'Травоядные', 'Растения', 'Грибы'],
      correctAnswer: 'Растения', difficulty: 'easy',
      explanation: 'Продуценты (растения) создают органику из неорганики с помощью фотосинтеза.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ГЕОГРАФИЯ
  // ══════════════════════════════════════════════════════════
  geography: [
    { id: 'ge1', subject: 'geography', topic: 'Казахстан',
      text: 'Какое место по площади занимает Казахстан в мире?',
      options: ['7-е', '8-е', '9-е', '10-е'], correctAnswer: '9-е', difficulty: 'easy',
      explanation: 'Казахстан — 9-я по площади страна (2 724 902 км²).' },
    { id: 'ge2', subject: 'geography', topic: 'Казахстан',
      text: 'С каким количеством государств граничит Казахстан?',
      options: ['3', '4', '5', '6'], correctAnswer: '5', difficulty: 'easy',
      explanation: 'Казахстан граничит с Россией, Китаем, Кыргызстаном, Узбекистаном, Туркменистаном.' },
    { id: 'ge3', subject: 'geography', topic: 'Горы',
      text: 'Самая высокая горная система Казахстана?',
      options: ['Алтай', 'Тянь-Шань', 'Каратау', 'Мугоджары'], correctAnswer: 'Тянь-Шань', difficulty: 'medium',
      explanation: 'Тянь-Шань — высочайшая система. Пик Хан-Тенгри — 6995 м.' },
    { id: 'ge4', subject: 'geography', topic: 'Горы',
      text: 'Высочайшая вершина Казахстана?',
      options: ['Белуха', 'Хан-Тенгри', 'Музтау', 'Талгар'],
      correctAnswer: 'Хан-Тенгри', difficulty: 'medium',
      explanation: 'Хан-Тенгри (6995 м) — высочайшая точка Казахстана.' },
    { id: 'ge5', subject: 'geography', topic: 'Климат',
      text: 'Какой климат характерен для большей части Казахстана?',
      options: ['Субтропический', 'Резко континентальный', 'Морской', 'Арктический'],
      correctAnswer: 'Резко континентальный', difficulty: 'easy',
      explanation: 'Большая удалённость от океанов — резко континентальный климат.' },
    { id: 'ge6', subject: 'geography', topic: 'Климат',
      text: 'Самая высокая температура в Казахстане фиксируется в:',
      options: ['Нур-Султане', 'Алматы', 'Кызылорде', 'Оскемене'],
      correctAnswer: 'Кызылорде', difficulty: 'medium',
      explanation: 'Южные регионы Казахстана (Кызылорда) — самые жаркие.' },
    { id: 'ge7', subject: 'geography', topic: 'Реки',
      text: 'Самая длинная река Казахстана?',
      options: ['Иртыш', 'Сырдарья', 'Или', 'Урал'], correctAnswer: 'Иртыш', difficulty: 'medium',
      explanation: 'Иртыш — самая длинная река в Казахстане (≈4248 км).' },
    { id: 'ge8', subject: 'geography', topic: 'Реки',
      text: 'Какое крупное озеро расположено на юге Казахстана?',
      options: ['Балхаш', 'Аральское море', 'Зайсан', 'Алаколь'],
      correctAnswer: 'Аральское море', difficulty: 'easy',
      explanation: 'Аральское море — бывшее крупное озеро на юге, ныне сильно обмелевшее.' },
    { id: 'ge9', subject: 'geography', topic: 'Столица',
      text: 'Как называется столица Казахстана с 2022 года?',
      options: ['Алматы', 'Астана', 'Нур-Султан', 'Акмола'], correctAnswer: 'Астана', difficulty: 'easy',
      explanation: 'В 2022 году городу возвращено название Астана.' },
    { id: 'ge10', subject: 'geography', topic: 'Картография',
      text: 'Какая картографическая проекция часто используется для морских карт?',
      options: ['Меркатора', 'Ламберта', 'Азимутальная', 'Поперечная'],
      correctAnswer: 'Меркатора', difficulty: 'medium',
      explanation: 'Проекция Меркатора сохраняет направления, удобна в мореплавании.' },
    { id: 'ge11', subject: 'geography', topic: 'Атмосфера',
      text: 'Как изменяется температура воздуха с подъёмом на каждые 100 м?',
      options: ['Растёт на 0.6°C', 'Падает на 0.6°C', 'Не изменяется', 'Падает на 6°C'],
      correctAnswer: 'Падает на 0.6°C', difficulty: 'medium',
      explanation: 'Стандартный вертикальный градиент: −0.6°C на каждые 100 м подъёма.' },
    { id: 'ge12', subject: 'geography', topic: 'Литосфера',
      text: 'На каком виде горных пород чаще всего образуются карстовые пещеры?',
      options: ['Гранит', '  Базальт', 'Известняк', 'Кварцит'],
      correctAnswer: 'Известняк', difficulty: 'medium',
      explanation: 'Известняк растворяется водой, образуя карстовые полости.' },
    { id: 'ge13', subject: 'geography', topic: 'Природные зоны',
      text: 'Самая большая природная зона Казахстана?',
      options: ['Тайга', 'Степь', 'Пустыня', 'Тундра'],
      correctAnswer: 'Степь', difficulty: 'easy',
      explanation: 'Степи занимают наибольшую площадь территории Казахстана.' },
    { id: 'ge14', subject: 'geography', topic: 'Население',
      text: 'Крупнейший город Казахстана по населению:',
      options: ['Астана', 'Алматы', 'Шымкент', 'Актобе'],
      correctAnswer: 'Алматы', difficulty: 'easy',
      explanation: 'Алматы — крупнейший город Казахстана по населению (≈2 млн чел.).' },
    { id: 'ge15', subject: 'geography', topic: 'Глобальные проблемы',
      text: 'Катастрофическое высыхание какого водоёма является одной из главных экологических проблем Казахстана?',
      options: ['Балхаш', 'Аральское море', 'Каспийское море', 'Зайсан'],
      correctAnswer: 'Аральское море', difficulty: 'easy',
      explanation: 'Высыхание Аральского моря — экологическая катастрофа XX века.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ИСТОРИЯ КАЗАХСТАНА
  // ══════════════════════════════════════════════════════════
  history_kz: [
    { id: 'hk1', subject: 'history_kz', topic: 'Казахское ханство',
      text: 'Год образования Казахского ханства?',
      options: ['1455', '1465', '1480', '1500'], correctAnswer: '1465', difficulty: 'easy',
      explanation: 'Казахское ханство основано около 1465 г. ханами Кереем и Жанибеком.' },
    { id: 'hk2', subject: 'history_kz', topic: 'Казахское ханство',
      text: 'Основатели Казахского ханства?',
      options: ['Абылай и Абулхаир', 'Керей и Жанибек', 'Тауке и Хакназар', 'Касым и Хакназар'],
      correctAnswer: 'Керей и Жанибек', difficulty: 'easy',
      explanation: 'Казахское ханство основали ханы Керей и Жанибек.' },
    { id: 'hk3', subject: 'history_kz', topic: 'Казахское ханство',
      text: 'При каком хане Казахское ханство достигло наибольшего расцвета в XVI в.?',
      options: ['Касым-хан', 'Хакназар', 'Аблай-хан', 'Тауке-хан'],
      correctAnswer: 'Касым-хан', difficulty: 'medium',
      explanation: 'Касым-хан (1511–1523) расширил ханство до 1 млн км².' },
    { id: 'hk4', subject: 'history_kz', topic: 'Джунгарские войны',
      text: 'Как называется период 1723–1727 гг.?',
      options: ['Ақтабан шұбырынды', 'Ұлы жеңіс', 'Орда жорығы', 'Анракай'],
      correctAnswer: 'Ақтабан шұбырынды', difficulty: 'medium',
      explanation: '"Ақтабан шұбырынды" — Великое бедствие, массовое отступление казахов.' },
    { id: 'hk5', subject: 'history_kz', topic: 'Джунгарские войны',
      text: 'В каком году произошла Анракайская битва — победа казахов над джунгарами?',
      options: ['1723', '1730', '1756', '1800'], correctAnswer: '1730', difficulty: 'medium',
      explanation: 'Анракайская битва — 1730 год, решающая победа казахов над джунгарами.' },
    { id: 'hk6', subject: 'history_kz', topic: 'Независимость',
      text: 'Год провозглашения независимости Казахстана?',
      options: ['1989', '1990', '1991', '1992'], correctAnswer: '1991', difficulty: 'easy',
      explanation: 'Казахстан провозгласил независимость 16 декабря 1991 года.' },
    { id: 'hk7', subject: 'history_kz', topic: 'Независимость',
      text: 'Первый Президент Казахстана:',
      options: ['Токаев', 'Назарбаев', 'Кунаев', 'Масимов'],
      correctAnswer: 'Назарбаев', difficulty: 'easy',
      explanation: 'Нурсултан Назарбаев — первый президент независимого Казахстана.' },
    { id: 'hk8', subject: 'history_kz', topic: 'Советский период',
      text: 'Когда Казахская АССР стала Казахской ССР?',
      options: ['1920', '1925', '1936', '1945'], correctAnswer: '1936', difficulty: 'medium',
      explanation: 'В 1936 году — преобразование в союзную республику.' },
    { id: 'hk9', subject: 'history_kz', topic: 'Советский период',
      text: 'Движение «Алаш» возникло в:',
      options: ['1905', '1913', '1917', '1920'], correctAnswer: '1917', difficulty: 'medium',
      explanation: 'Партия «Алаш» образована в 1917 г. для защиты интересов казахского народа.' },
    { id: 'hk10', subject: 'history_kz', topic: 'Древний период',
      text: 'Племена саков населяли территорию Казахстана в:',
      options: ['III−I тыс. до н.э.', 'VIII−III вв. до н.э.', 'I−IV вв. н.э.', 'V−VIII вв. н.э.'],
      correctAnswer: 'VIII−III вв. до н.э.', difficulty: 'medium',
      explanation: 'Сакские племена — VIII−III вв. до н.э., раннежелезный век.' },
    { id: 'hk11', subject: 'history_kz', topic: 'Культура',
      text: 'Автор поэмы «Слова назидания» (Қара сөздер)?',
      options: ['Жамбыл', 'Абай', 'Дулат', 'Биржан'],
      correctAnswer: 'Абай', difficulty: 'easy',
      explanation: 'Абай Кунанбаев — автор «Слов назидания» (Қара сөздер).' },
    { id: 'hk12', subject: 'history_kz', topic: 'Культура',
      text: '"Козы Корпеш — Баян Сулу" — это:',
      options: ['Авторский роман', 'Народный эпос', 'Историческая хроника', 'Государственный документ'],
      correctAnswer: 'Народный эпос', difficulty: 'medium',
      explanation: 'Козы Корпеш — Баян Сулу — казахский народный лирический эпос.' },
    { id: 'hk13', subject: 'history_kz', topic: 'Тюркские каганаты',
      text: 'Первый Тюркский каганат возник в:',
      options: ['III в.', 'IV в.', 'VI в.', 'VIII в.'], correctAnswer: 'VI в.', difficulty: 'medium',
      explanation: 'Первый Тюркский каганат образован в 552 году н.э.' },
    { id: 'hk14', subject: 'history_kz', topic: 'Российская колонизация',
      text: 'Когда младший жуз принял российское подданство?',
      options: ['1700', '1731', '1760', '1800'], correctAnswer: '1731', difficulty: 'medium',
      explanation: 'В 1731 г. Абулхаир-хан принял подданство России, начав присоединение.' },
    { id: 'hk15', subject: 'history_kz', topic: 'Восстания',
      text: 'Руководитель восстания 1916 года в Казахстане:',
      options: ['Кенесары', 'Амангельды Иманов', 'Исатай Тайманов', 'Аблай-хан'],
      correctAnswer: 'Амангельды Иманов', difficulty: 'medium',
      explanation: 'Амангельды Иманов — один из главных руководителей восстания 1916 г.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ВСЕМИРНАЯ ИСТОРИЯ
  // ══════════════════════════════════════════════════════════
  world_history: [
    { id: 'wh1', subject: 'world_history', topic: 'Древний Рим',
      text: 'В каком году пала Западная Римская империя?',
      options: ['395', '410', '476', '527'], correctAnswer: '476', difficulty: 'medium',
      explanation: '476 н.э. — свержение Ромула Августула.' },
    { id: 'wh2', subject: 'world_history', topic: 'Древний Египет',
      text: 'Вдоль какой реки располагался Древний Египет?',
      options: ['Нил', 'Тигр', 'Енисей', 'Хуанхэ'], correctAnswer: 'Нил', difficulty: 'easy',
      explanation: 'Древний Египет образовался вдоль реки Нил.' },
    { id: 'wh3', subject: 'world_history', topic: 'Средневековье',
      text: 'Великая Хартия вольностей подписана в:',
      options: ['1066', '1215', '1415', '1492'], correctAnswer: '1215', difficulty: 'medium',
      explanation: 'Magna Carta — 1215 год, король Иоанн Безземельный.' },
    { id: 'wh4', subject: 'world_history', topic: 'Средневековье',
      text: 'Монгольская империя достигла наибольших размеров при:',
      options: ['Чингисхане', 'Хубилае', 'Батые', 'Тамерлане'],
      correctAnswer: 'Хубилае', difficulty: 'medium',
      explanation: 'При Хубилай-хане (1260–1294) Монгольская империя была наибольшей.' },
    { id: 'wh5', subject: 'world_history', topic: 'Революции',
      text: 'Великая французская революция началась в:',
      options: ['1776', '1789', '1799', '1804'], correctAnswer: '1789', difficulty: 'easy',
      explanation: '1789 год — взятие Бастилии 14 июля.' },
    { id: 'wh6', subject: 'world_history', topic: 'Революции',
      text: 'Декларация независимости США подписана в:',
      options: ['1773', '1776', '1783', '1789'], correctAnswer: '1776', difficulty: 'easy',
      explanation: '4 июля 1776 года — принятие Декларации независимости США.' },
    { id: 'wh7', subject: 'world_history', topic: 'XX век',
      text: 'Год окончания Второй мировой войны?',
      options: ['1943', '1944', '1945', '1946'], correctAnswer: '1945', difficulty: 'easy',
      explanation: '1945 год: Европа — май, Тихий океан — сентябрь.' },
    { id: 'wh8', subject: 'world_history', topic: 'XX век',
      text: 'В каком году началась Первая мировая война?',
      options: ['1912', '1914', '1916', '1918'], correctAnswer: '1914', difficulty: 'easy',
      explanation: 'Первая мировая война: 1914–1918 гг.' },
    { id: 'wh9', subject: 'world_history', topic: 'Великие открытия',
      text: 'В каком году Колумб достиг Америки?',
      options: ['1488', '1492', '1498', '1519'], correctAnswer: '1492', difficulty: 'easy',
      explanation: '12 октября 1492 года Колумб достиг берегов Америки.' },
    { id: 'wh10', subject: 'world_history', topic: 'Великие открытия',
      text: 'Кто первым совершил кругосветное плавание?',
      options: ['Колумб', 'Васко да Гама', 'Магеллан', 'Дрейк'],
      correctAnswer: 'Магеллан', difficulty: 'medium',
      explanation: 'Фернан Магеллан начал первое кругосветное путешествие (1519–1522).' },
    { id: 'wh11', subject: 'world_history', topic: 'Промышленная революция',
      text: 'Промышленная революция началась в:',
      options: ['Франции', 'Германии', 'Великобритании', 'США'],
      correctAnswer: 'Великобритании', difficulty: 'easy',
      explanation: 'Промышленная революция XVIII в. началась в Великобритании.' },
    { id: 'wh12', subject: 'world_history', topic: 'Реформация',
      text: 'Кто положил начало Реформации в Европе?',
      options: ['Кальвин', 'Мартин Лютер', 'Эразм Роттердамский', 'Томас Мор'],
      correctAnswer: 'Мартин Лютер', difficulty: 'medium',
      explanation: 'Мартин Лютер в 1517 г. выступил с 95 тезисами против индульгенций.' },
    { id: 'wh13', subject: 'world_history', topic: 'Холодная война',
      text: 'Год распада СССР?',
      options: ['1989', '1990', '1991', '1993'], correctAnswer: '1991', difficulty: 'easy',
      explanation: 'СССР прекратил существование 25 декабря 1991 года.' },
    { id: 'wh14', subject: 'world_history', topic: 'Древняя Греция',
      text: 'Первые Олимпийские игры прошли в:',
      options: ['776 до н.э.', '490 до н.э.', '431 до н.э.', '323 до н.э.'],
      correctAnswer: '776 до н.э.', difficulty: 'medium',
      explanation: 'Первые Олимпийские игры состоялись в 776 г. до н.э. в Олимпии.' },
    { id: 'wh15', subject: 'world_history', topic: 'Вторая мировая',
      text: 'Когда Германия напала на СССР (начало Великой Отечественной войны)?',
      options: ['1 сентября 1939', '22 июня 1941', '7 декабря 1941', '6 июня 1944'],
      correctAnswer: '22 июня 1941', difficulty: 'easy',
      explanation: '22 июня 1941 г. — нападение Германии на СССР, начало ВОВ.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  АНГЛИЙСКИЙ ЯЗЫК
  // ══════════════════════════════════════════════════════════
  english: [
    { id: 'en1', subject: 'english', topic: 'Present Perfect',
      text: '"She ___ (work) here since 2020."',
      options: ['works', 'worked', 'has worked', 'is working'], correctAnswer: 'has worked', difficulty: 'medium',
      explanation: '"Since" требует Present Perfect: "She has worked here since 2020."' },
    { id: 'en2', subject: 'english', topic: 'Синонимы / антонимы',
      text: 'Synonym of "happy":',
      options: ['Sad', 'Joyful', 'Angry', 'Tired'], correctAnswer: 'Joyful', difficulty: 'easy',
      explanation: '"Joyful" = full of joy. Синоним "happy".' },
    { id: 'en3', subject: 'english', topic: 'Синонимы / антонимы',
      text: 'Антоним к слову "happy":',
      options: ['glad', 'sad', 'joyful', 'merry'], correctAnswer: 'sad', difficulty: 'easy',
      explanation: '"Sad" — грустный, противоположность "happy".' },
    { id: 'en4', subject: 'english', topic: 'Косвенная речь',
      text: '"She asked me ___ I wanted to go."',
      options: ['that', 'what', 'which', 'how'], correctAnswer: 'what', difficulty: 'medium',
      explanation: 'Indirect question: "She asked me what I wanted."' },
    { id: 'en5', subject: 'english', topic: 'Предлоги',
      text: '"I will meet you ___ Monday ___ 9 a.m."',
      options: ['in/at', 'on/at', 'at/on', 'on/in'], correctAnswer: 'on/at', difficulty: 'easy',
      explanation: '"On" — дни недели, "at" — время. On Monday at 9 a.m.' },
    { id: 'en6', subject: 'english', topic: 'Словообразование',
      text: 'Noun form of "discover"?',
      options: ['discovers', 'discoverable', 'discovery', 'discoverer'], correctAnswer: 'discovery', difficulty: 'easy',
      explanation: '"Discovery" — существительное от "discover".' },
    { id: 'en7', subject: 'english', topic: 'Артикли',
      text: '"She is ___ best student in the class."',
      options: ['a', 'an', 'the', '—'], correctAnswer: 'the', difficulty: 'easy',
      explanation: 'Перед превосходной степенью используется определённый артикль "the".' },
    { id: 'en8', subject: 'english', topic: 'Артикли',
      text: '"I saw ___ interesting film yesterday."',
      options: ['a', 'an', 'the', '—'], correctAnswer: 'an', difficulty: 'easy',
      explanation: '"An" используется перед словами, начинающимися на гласный звук.' },
    { id: 'en9', subject: 'english', topic: 'Времена глагола',
      text: '"By the time he arrived, she ___ (leave)."',
      options: ['left', 'has left', 'had left', 'was leaving'],
      correctAnswer: 'had left', difficulty: 'medium',
      explanation: 'Past Perfect (had left) — действие до другого прошедшего.' },
    { id: 'en10', subject: 'english', topic: 'Времена глагола',
      text: '"They ___ (play) football when it started to rain."',
      options: ['played', 'were playing', 'had played', 'play'],
      correctAnswer: 'were playing', difficulty: 'medium',
      explanation: 'Past Continuous — длящееся действие в прошлом.' },
    { id: 'en11', subject: 'english', topic: 'Условные предложения',
      text: '"If it ___ (rain), we will stay at home."',
      options: ['rains', 'rained', 'will rain', 'would rain'],
      correctAnswer: 'rains', difficulty: 'medium',
      explanation: 'Conditional I (реальное): If + Present Simple, will + V.' },
    { id: 'en12', subject: 'english', topic: 'Пассивный залог',
      text: '"The letter ___ (write) by Mary."',
      options: ['wrote', 'was written', 'has written', 'is writing'],
      correctAnswer: 'was written', difficulty: 'medium',
      explanation: 'Passive voice: was/were + V3 (Past Simple Passive).' },
    { id: 'en13', subject: 'english', topic: 'Фразовые глаголы',
      text: '"Please ___ the light — it\'s dark here."',
      options: ['turn up', 'turn on', 'turn off', 'turn down'],
      correctAnswer: 'turn on', difficulty: 'easy',
      explanation: '"Turn on" — включить (электроприбор, свет).' },
    { id: 'en14', subject: 'english', topic: 'Словообразование',
      text: 'Adjective form of "beauty"?',
      options: ['beautify', 'beautifully', 'beautiful', 'beautiness'],
      correctAnswer: 'beautiful', difficulty: 'easy',
      explanation: '"Beautiful" — прилагательное от "beauty".' },
    { id: 'en15', subject: 'english', topic: 'Союзы',
      text: '"He works hard ___ he wants to succeed."',
      options: ['so', 'because', 'but', 'although'],
      correctAnswer: 'because', difficulty: 'easy',
      explanation: '"Because" — причинный союз, объясняет причину действия.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  РУССКИЙ ЯЗЫК
  // ══════════════════════════════════════════════════════════
  russian: [
    { id: 'ru1', subject: 'russian', topic: 'Орфография',
      text: 'Как правильно: «пр_обрести»?',
      options: ['преобрести', 'приобрести', 'пр\'обрести', 'прообрести'],
      correctAnswer: 'приобрести', difficulty: 'medium',
      explanation: 'Приставка ПРИ- — значение присоединения: приобрести.' },
    { id: 'ru2', subject: 'russian', topic: 'Орфография',
      text: 'Как пишется: «бе_шумный»?',
      options: ['безшумный', 'бесшумный', 'бешумный', 'безшумный'],
      correctAnswer: 'бесшумный', difficulty: 'easy',
      explanation: 'Перед глухой согласной «ш» приставка БЕС-: бесшумный.' },
    { id: 'ru3', subject: 'russian', topic: 'Орфография',
      text: 'Верное написание: «не/ни_ когда»?',
      options: ['никогда', 'негогда', 'не когда', 'ни когда'],
      correctAnswer: 'никогда', difficulty: 'easy',
      explanation: 'В отрицательных наречиях под ударением — НЕ, без ударения — НИ. «Никогда» — без ударения на приставке.' },
    { id: 'ru4', subject: 'russian', topic: 'Пунктуация',
      text: 'Правильная пунктуация: «Солнце зашло ___ стало темнее»',
      options: ['Солнце зашло, и стало темнее.', 'Солнце зашло и, стало темнее.',
                 'Солнце, зашло и стало темнее.', 'Солнце зашло и стало, темнее.'],
      correctAnswer: 'Солнце зашло, и стало темнее.', difficulty: 'easy',
      explanation: 'В ССП перед союзом «и» ставится запятая.' },
    { id: 'ru5', subject: 'russian', topic: 'Пунктуация',
      text: 'Нужна ли запятая: «Он читал книгу (,) лёжа на диване»?',
      options: ['Да, деепричастный оборот', 'Нет, не нужна', 'Да, однородные члены', 'Да, обращение'],
      correctAnswer: 'Да, деепричастный оборот', difficulty: 'medium',
      explanation: 'Деепричастный оборот «лёжа на диване» выделяется запятыми.' },
    { id: 'ru6', subject: 'russian', topic: 'Морфология',
      text: 'Часть речи слова «бегом»?',
      options: ['Существительное', 'Наречие', 'Деепричастие', 'Глагол'],
      correctAnswer: 'Наречие', difficulty: 'medium',
      explanation: '"Бегом" — наречие (как?), неизменяемое слово.' },
    { id: 'ru7', subject: 'russian', topic: 'Морфология',
      text: 'Какая часть речи «вдруг»?',
      options: ['Прилагательное', 'Существительное', 'Наречие', 'Союз'],
      correctAnswer: 'Наречие', difficulty: 'easy',
      explanation: '"Вдруг" отвечает на вопрос «как?» — наречие.' },
    { id: 'ru8', subject: 'russian', topic: 'Лексика',
      text: 'Антоним слова «скупой»:',
      options: ['Жадный', 'Щедрый', 'Богатый', 'Бедный'],
      correctAnswer: 'Щедрый', difficulty: 'easy',
      explanation: 'Антоним «скупой» — «щедрый».' },
    { id: 'ru9', subject: 'russian', topic: 'Лексика',
      text: 'Синоним слова «грустить»:',
      options: ['Радоваться', 'Печалиться', 'Смеяться', 'Удивляться'],
      correctAnswer: 'Печалиться', difficulty: 'easy',
      explanation: '"Печалиться" — синоним "грустить".' },
    { id: 'ru10', subject: 'russian', topic: 'Синтаксис',
      text: 'Сложноподчинённое предложение:',
      options: ['Пошёл дождь, и мы остались дома.', 'Мы остались дома, потому что пошёл дождь.',
                 'Пошёл дождь; мы остались дома.', 'Мы остались дома: пошёл дождь.'],
      correctAnswer: 'Мы остались дома, потому что пошёл дождь.', difficulty: 'medium',
      explanation: 'СПП — с подчинительным союзом «потому что».' },
    { id: 'ru11', subject: 'russian', topic: 'Синтаксис',
      text: 'Какое предложение является простым?',
      options: [
        'Дождь прошёл, и стало прохладно.',
        'Студент, который хорошо учится, получит стипендию.',
        'Солнце светило ярко.',
        'Когда я пришёл, все уже ушли.'
      ], correctAnswer: 'Солнце светило ярко.', difficulty: 'easy',
      explanation: '"Солнце светило ярко" — одна грамматическая основа, простое предложение.' },
    { id: 'ru12', subject: 'russian', topic: 'Фонетика',
      text: 'Сколько звуков в слове «ёлка»?',
      options: ['4', '5', '6', '3'], correctAnswer: '5', difficulty: 'medium',
      explanation: 'Ё = [й][о], л, к, а. Итого 5 звуков: [й-о-л-к-а].' },
    { id: 'ru13', subject: 'russian', topic: 'Орфография',
      text: 'Как пишется «не» с прилагательным «небольшой»?',
      options: ['Не большой', 'Небольшой', 'Не-большой', 'Нибольшой'],
      correctAnswer: 'Небольшой', difficulty: 'easy',
      explanation: 'Прилагательное с «не» пишется слитно, если можно заменить синонимом (маленький).' },
    { id: 'ru14', subject: 'russian', topic: 'Орфография',
      text: 'Верное написание: «(не)зависимый»?',
      options: ['независимый', 'не зависимый', 'не-зависимый', 'независемый'],
      correctAnswer: 'независимый', difficulty: 'medium',
      explanation: 'Пишется слитно, если нет противопоставления с «а».' },
    { id: 'ru15', subject: 'russian', topic: 'Морфология',
      text: 'Как изменяется имя прилагательное?',
      options: [
        'По лицам и числам',
        'По родам, числам и падежам',
        'Только по падежам',
        'Не изменяется'
      ], correctAnswer: 'По родам, числам и падежам', difficulty: 'easy',
      explanation: 'Имя прилагательное согласуется с существительным: род, число, падеж.' },
  ],

  // ══════════════════════════════════════════════════════════
  //  ИНФОРМАТИКА
  // ══════════════════════════════════════════════════════════
  informatics: [
    { id: 'it1', subject: 'informatics', topic: 'Системы счисления',
      text: '1010₂ в десятичной системе =',
      options: ['8', '10', '12', '14'], correctAnswer: '10', difficulty: 'easy',
      explanation: '1×8 + 0×4 + 1×2 + 0×1 = 10.' },
    { id: 'it2', subject: 'informatics', topic: 'Системы счисления',
      text: 'Переведите 25₁₀ в двоичную систему:',
      options: ['10101', '11001', '10011', '11010'], correctAnswer: '11001', difficulty: 'medium',
      explanation: '25 = 16+8+1 = 2⁴+2³+2⁰ = 11001₂.' },
    { id: 'it3', subject: 'informatics', topic: 'Системы счисления',
      text: 'FF₁₆ в десятичной = ?',
      options: ['225', '240', '255', '256'], correctAnswer: '255', difficulty: 'medium',
      explanation: 'F=15. FF = 15×16 + 15 = 240+15 = 255.' },
    { id: 'it4', subject: 'informatics', topic: 'Алгоритмы',
      text: 'Сложность быстрой сортировки в среднем?',
      options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'],
      correctAnswer: 'O(n log n)', difficulty: 'medium',
      explanation: 'Quicksort в среднем — O(n log n).' },
    { id: 'it5', subject: 'informatics', topic: 'Алгоритмы',
      text: 'Что такое рекурсия в программировании?',
      options: [
        'Вызов другой функции',
        'Функция, вызывающая саму себя',
        'Цикл с условием',
        'Массив функций'
      ], correctAnswer: 'Функция, вызывающая саму себя', difficulty: 'easy',
      explanation: 'Рекурсия — функция, которая в своём теле вызывает себя.' },
    { id: 'it6', subject: 'informatics', topic: 'Python',
      text: 'Что выведет: print(2 ** 8)?',
      options: ['16', '64', '256', '512'], correctAnswer: '256', difficulty: 'easy',
      explanation: '** — степень. 2⁸ = 256.' },
    { id: 'it7', subject: 'informatics', topic: 'Python',
      text: 'Тип данных переменной x = "hello" в Python?',
      options: ['int', 'float', 'str', 'bool'], correctAnswer: 'str', difficulty: 'easy',
      explanation: 'Строки в Python имеют тип str (string).' },
    { id: 'it8', subject: 'informatics', topic: 'Python',
      text: 'Что выведет: print(len([1,2,3,4,5]))?',
      options: ['4', '5', '6', '15'], correctAnswer: '5', difficulty: 'easy',
      explanation: 'len() возвращает длину списка: 5 элементов.' },
    { id: 'it9', subject: 'informatics', topic: 'SQL',
      text: 'Оператор SQL для выборки данных?',
      options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], correctAnswer: 'SELECT', difficulty: 'easy',
      explanation: 'SELECT — выборка (чтение) данных из таблицы.' },
    { id: 'it10', subject: 'informatics', topic: 'SQL',
      text: 'Какой оператор SQL удаляет строки из таблицы?',
      options: ['DROP', 'DELETE', 'REMOVE', 'ERASE'], correctAnswer: 'DELETE', difficulty: 'easy',
      explanation: 'DELETE FROM table WHERE ... — удаляет строки по условию.' },
    { id: 'it11', subject: 'informatics', topic: 'Сети',
      text: 'IP-адрес — это:',
      options: ['Имя компьютера', 'Уникальный числовой идентификатор устройства', 'Пароль Wi-Fi', 'Название браузера'],
      correctAnswer: 'Уникальный числовой идентификатор устройства', difficulty: 'easy',
      explanation: 'IP-адрес (напр. 192.168.1.1) — идентификатор устройства в сети.' },
    { id: 'it12', subject: 'informatics', topic: 'Сети',
      text: 'Протокол HTTP используется для:',
      options: ['Отправки e-mail', 'Передачи веб-страниц', 'Передачи файлов', 'Безопасного соединения'],
      correctAnswer: 'Передачи веб-страниц', difficulty: 'easy',
      explanation: 'HTTP (HyperText Transfer Protocol) — протокол для передачи веб-страниц.' },
    { id: 'it13', subject: 'informatics', topic: 'Устройства компьютера',
      text: 'Какой компонент выполняет арифметические и логические операции?',
      options: ['Оперативная память', 'Жёсткий диск', 'Процессор', 'Видеокарта'],
      correctAnswer: 'Процессор', difficulty: 'easy',
      explanation: 'Процессор (CPU) отвечает за вычисления и логику.' },
    { id: 'it14', subject: 'informatics', topic: 'Логика',
      text: 'Результат: True AND False в Python?',
      options: ['True', 'False', '1', 'None'], correctAnswer: 'False', difficulty: 'easy',
      explanation: 'AND: оба должны быть True. True AND False = False.' },
    { id: 'it15', subject: 'informatics', topic: 'Логика',
      text: 'Результат: NOT True в Python?',
      options: ['True', 'False', '0', 'None'], correctAnswer: 'False', difficulty: 'easy',
      explanation: 'NOT инвертирует значение: NOT True = False.' },
  ],
};

// ─── Диагностические вопросы (10 на предмет: 4 easy + 4 medium + 2 hard) ─────
export function getDiagnosticQuestions(subjectIds: string[]): Question[] {
  const result: Question[] = [];
  for (const sid of subjectIds) {
    const qs = QUESTIONS_BANK[sid];
    if (!qs) continue;
    const easy   = qs.filter(q => q.difficulty === 'easy').slice(0, 4);
    const medium = qs.filter(q => q.difficulty === 'medium').slice(0, 4);
    const hard   = qs.filter(q => q.difficulty === 'hard').slice(0, 2);
    // Добираем до 10 если нужно
    const selected = [...easy, ...medium, ...hard].slice(0, 10);
    result.push(...selected);
  }
  return result;
}

export function getSubjectQuestions(subjectId: string): Question[] {
  return QUESTIONS_BANK[subjectId] || [];
}

export const REQUIRED_SUBJECTS = ALL_SUBJECTS.filter(s => s.required).map(s => s.id);
